version: '2'
services:
  mygallery-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/MyGallery/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=MyGallery
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
